// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTvXk3glbEDMGlOEKbSF7zVRwPo1Efkkg',
    appId: '1:34124335901:android:b9c8a07769a5afebf86ff4',
    messagingSenderId: '39492395200',
    projectId: 'ankoot-822ac',
    storageBucket: 'avdkitchenapp.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDTvXk3glbEDMGlOEKbSF7zVRwPo1Efkkg",
      authDomain: "ankoot-822ac.firebaseapp.com",
      projectId: "ankoot-822ac",
      storageBucket: "ankoot-822ac.firebasestorage.app",
      messagingSenderId: "39492395200",
      appId: "1:39492395200:web:215c66aace6824ef9e0d25",
      measurementId: "G-4TDJ3MCTJC"
  );


  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTvXk3glbEDMGlOEKbSF7zVRwPo1Efkkg',
    appId: '1:39492395200:ios:e7c8bbf6762b985c9e0d25',
    messagingSenderId: '39492395200',
    projectId: 'ankoot-822ac',
  );
}
